rel_stages = [
    "1-1",
    "1-2",
    "1-3",
]

[[AsmTile]]
name = "start"
pos = [0, 0]
text = "ケアマネジありがと"
explain = "All start with this tile"
show_rely = []
light_rely = []

[[AsmTile]]
name = "end"
pos = [0, 3]
text = "这是一个中文文本"
explain = "Collect all clues"
show_rely = ["start"]
light_rely = ["reason1", "reason2", "start"]

[[AsmTile]]
name = "futher"
pos = [-2, 4]
text = "这是一个更深的推论"
explain = "Collect all clues 2"
show_rely = ["end"]
light_rely = ["reason3", "reason4", "end"]

[[ReasonTile]]
name = "reason1"
pos = [0, 2]
clue = "1-1:1"
show_rely = ["end"]

[[ReasonTile]]
name = "reason2"
pos = [1, 2]
clue = "1-1:2"
show_rely = ["end"]

[[ConnTile]]
name = "conn1"
pos = [0, 1]
show_rely = ["start"]

[[AckTile]]
name = "ack1"
pos = [0, 4]
next_stage = "2-1"
show_rely = ["end"]

[[ReasonTile]]
name = "reason3"
pos = [-3, 4]
clue = "1-2:1"
show_rely = ["futher"]

[[ReasonTile]]
name = "reason4"
pos = [-3, 5]
clue = "1-2:2"
show_rely = ["futher"]

[[AckTile]]
name = "ack2"
pos = [-2, 5]
next_stage = "2-1"
show_rely = ["futher"]
